/*
 * Copyright (c) 2021, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "ti_msp_dl_config.h"

/* Address in main memory to write to */
#define MAIN_BASE_ADDRESS (0x0001FB00)

volatile DL_FLASHCTL_COMMAND_STATUS gCmdStatus;

/* Codes to understand where error occured */
#define NO_ERROR 0
#define ERROR_ERASE 1
#define ERROR_8BIT_W 2
#define ERROR_16BIT_W 3
#define ERROR_32BIT_W 4
#define ERROR_64BIT_W 5

volatile uint8_t gErrorType = NO_ERROR;

uint32_t yellow_led_pins[] = {
    GPIO_LEDS_Y12_PIN,
    GPIO_LEDS_Y1_PIN, 
    GPIO_LEDS_Y2_PIN, 
    GPIO_LEDS_Y3_PIN, 
    GPIO_LEDS_Y4_PIN, 
    GPIO_LEDS_Y5_PIN, 
    GPIO_LEDS_Y6_PIN, 
    GPIO_LEDS_Y7_PIN, 
    GPIO_LEDS_Y8_PIN, 
    GPIO_LEDS_Y9_PIN, 
    GPIO_LEDS_Y10_PIN, 
    GPIO_LEDS_Y11_PIN
};

uint32_t red_led_pins[] = {
    GPIO_LEDS_R12_PIN,
    GPIO_LEDS_R1_PIN, 
    GPIO_LEDS_R2_PIN, 
    GPIO_LEDS_R3_PIN, 
    GPIO_LEDS_R4_PIN, 
    GPIO_LEDS_R5_PIN, 
    GPIO_LEDS_R6_PIN, 
    GPIO_LEDS_R7_PIN, 
    GPIO_LEDS_R8_PIN, 
    GPIO_LEDS_R9_PIN, 
    GPIO_LEDS_R10_PIN, 
    GPIO_LEDS_R11_PIN
};

void wait_for_button_release(void) {
    // Wait for button press and release
    NVIC_EnableIRQ(GPIO_BUTTONS_INT_IRQN);
    while (DL_GPIO_readPins(
            GPIO_BUTTONS_PORT, GPIO_BUTTONS_BUTTON_PIN)) {
        __WFI();
    }
    delay_cycles(4000000);
    while (!DL_GPIO_readPins(
            GPIO_BUTTONS_PORT, GPIO_BUTTONS_BUTTON_PIN)) {
        __WFI();
    }
    NVIC_DisableIRQ(GPIO_BUTTONS_INT_IRQN);
}

volatile int success_12 = 0;
volatile int success_1 = 0;


int main(void)
{
    SYSCFG_DL_init();

// Display fash memory counter value
// Wait for button press to clear

    uint32_t all_leds = 0;
    for (int j = 0; j < 12; j++) {
        all_leds = all_leds | red_led_pins[j];
        all_leds = all_leds | yellow_led_pins[j];
        DL_GPIO_clearPins(GPIO_LEDS_PORT, all_leds);
        delay_cycles(320);
    }

    // All leds on.

    wait_for_button_release();

    // Turn off all LEDs
    DL_GPIO_setPins(GPIO_LEDS_PORT, all_leds);

    volatile uint32_t* a;
    for (int j = 0; j < 144; j++) {
        a = (uint32_t *)(MAIN_BASE_ADDRESS + j*8); 
        if (*a != (j+1)) {
            break;
        }
        else {
            success_1++;
            if (success_1 == 12) {
                success_1 = 0;
                success_12++;
            }
        }
    }

    volatile uint32_t leds_to_light = 0;
    for (int j = 0; j < 12; j++) {
        if (j >= success_1) {
            break;
        }
        leds_to_light = leds_to_light | yellow_led_pins[j];
    }
    for (int j = 0; j < 12; j++) {
        if (j >= success_12) {
            break;
        }
        leds_to_light = leds_to_light | red_led_pins[j];
    }
    
    // Display success
    DL_GPIO_clearPins(GPIO_LEDS_PORT, leds_to_light);

    if ((success_1 == 0) && (success_12==0)) {
        DL_GPIO_clearPins(GPIO_LEDS_PORT, GPIO_LEDS_R6_PIN);
    }

    wait_for_button_release();

    /* Unprotect sector in main memory with ECC generated by hardware */
    DL_FlashCTL_unprotectSector(
        FLASHCTL, MAIN_BASE_ADDRESS, DL_FLASHCTL_REGION_SELECT_MAIN);
    /* Erase sector in main memory */
    gCmdStatus = DL_FlashCTL_eraseMemoryFromRAM(
        FLASHCTL, MAIN_BASE_ADDRESS, DL_FLASHCTL_COMMAND_SIZE_SECTOR);
    if (gCmdStatus == DL_FLASHCTL_COMMAND_STATUS_FAILED) {
        /* If command was not successful, set error flag */
        gErrorType = ERROR_ERASE;
    }

    if (gErrorType != NO_ERROR) {
        __BKPT(0); //Trap
    }


    // Turn off ALL (yellow and red) LEDs
    DL_GPIO_setPins(GPIO_LEDS_PORT, all_leds);
    DL_GPIO_clearPins(GPIO_LEDS_PORT, GPIO_LEDS_R12_PIN);

    wait_for_button_release();

    DL_GPIO_setPins(GPIO_LEDS_PORT, GPIO_LEDS_R12_PIN);

    // Get everything ready for flashing timestamps
    DL_TimerG_startCounter(TIMER_0_INST);


    // Final wait for trigger

    // POWER DOWN PCB HERE!

    // wait_for_button_release(); // Too much power!

    DL_GPIO_clearInterruptStatus(GPIO_BUTTONS_PORT, GPIO_BUTTONS_BUTTON_PIN);
    
    NVIC_EnableIRQ(GPIO_BUTTONS_INT_IRQN);
    while (DL_GPIO_readPins(
            GPIO_BUTTONS_PORT, GPIO_BUTTONS_BUTTON_PIN)) {
        __WFI();
    }
    NVIC_DisableIRQ(GPIO_BUTTONS_INT_IRQN);
    // // change button input to output
    IOMUX->SECCFG.PINCM[GPIO_BUTTONS_BUTTON_IOMUX] =
        IOMUX_PINCM_PC_CONNECTED | ((uint32_t) 0x00000001);


    NVIC_EnableIRQ(TIMER_0_INST_INT_IRQN);

    uint32_t d;
    for (int i = 0; i < 144; i++) {
        d = i + 1;
       /* 32-bit write to flash in main memory with ECC generated by hardware */
       DL_FlashCTL_unprotectSector(
            FLASHCTL, MAIN_BASE_ADDRESS, DL_FLASHCTL_REGION_SELECT_MAIN);
        gCmdStatus = DL_FlashCTL_programMemoryFromRAM32WithECCGenerated(
            FLASHCTL, (MAIN_BASE_ADDRESS + (i)*8), &d);
        __WFI();
    }

    // Trap when we're done, and burn those watts
    while(1) {
    };

}



void TIMER_0_INST_IRQHandler(void)
{
    switch (DL_TimerG_getPendingInterrupt(TIMER_0_INST)) {
        case DL_TIMER_IIDX_ZERO:

            break;
        default:
            break;
    }
}

void GROUP1_IRQHandler(void)
{
    uint32_t gpioA = DL_GPIO_getPendingInterrupt(GPIO_BUTTONS_PORT);
    // read should clear interrupt
}
